"""Adding encrypted files to migration

Revision ID: 4a4bed19ba9c
Revises: 0f2106df697f
Create Date: 2025-08-18 00:55:53.706184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4bed19ba9c'
down_revision: Union[str, Sequence[str], None] = '0f2106df697f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encrypted_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('download_token', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('key', sa.LargeBinary(), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encrypted_files_download_token'), 'encrypted_files', ['download_token'], unique=True)
    op.create_index(op.f('ix_encrypted_files_id'), 'encrypted_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encrypted_files_id'), table_name='encrypted_files')
    op.drop_index(op.f('ix_encrypted_files_download_token'), table_name='encrypted_files')
    op.drop_table('encrypted_files')
    # ### end Alembic commands ###
