name: CI - Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies (with fallback)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest \
            || pip install fastapi python-multipart cryptography alembic "sqlalchemy>=2.0" "psycopg2-binary>=2.9" pytest

      - name: Run tests
        run: pytest -q
